name: Deployment

on:
  push:
    branches: [master]

jobs:
  Deploy-prod-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Where i am
        run: |
          ls

      - name: Where i am
        run: |
          pwd

      - name: Auth to GCR and GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Build image
        run: |-
          docker build -t eu.gcr.io/${{ secrets.PROJECT_ID }}/boutiquefrancaisedockerise -t eu.gcr.io/${{ secrets.PROJECT_ID }}/boutiquefrancaisedockerise:$GITHUB_SHA .

      - run: |
          gcloud auth configure-docker -q

      # Push image to Google Container Registry
      - name: Push image
        run: |-
          docker push eu.gcr.io/${{ secrets.PROJECT_ID }}/boutiquefrancaisedockerise